export const support = [
  {
    title:
      "How can I get FAQ Page to work with Google assistant powered devices?",
    para: "The FAQPage code generated by this FAQ Page Schema Generator tool will be picked up by both Google Search and Google Assistant powered devices. You just need to install it on your page, you can check if it's working as expected by validating the page with Google’s Rich Result Testing tool. You don't need to do anything extra for it to be picked up by Google assistant powered devices.",
  },
  {
    title: "Does FAQ Snippets work on mobile or desktop?",
    para: "The FAQPage code generated by this FAQ Page Schema Generator tool will be picked up by both Google Search and Google Assistant powered devices. You just need to install it on your page, you can check if it's working as expected by validating the page with Google’s Rich Result Testing tool. You don't need to do anything extra for it to be picked up by Google assistant powered devices.",
  },
  {
    title: "What is the difference between FAQ and QA?",
    para: "The FAQPage code generated by this FAQ Page Schema Generator tool will be picked up by both Google Search and Google Assistant powered devices. You just need to install it on your page, you can check if it's working as expected by validating the page with Google’s Rich Result Testing tool. You don't need to do anything extra for it to be picked up by Google assistant powered devices.",
  },
  {
    title: "Is there a month-to-month payment option?",
    para: "The FAQPage code generated by this FAQ Page Schema Generator tool will be picked up by both Google Search and Google Assistant powered devices. You just need to install it on your page, you can check if it's working as expected by validating the page with Google’s Rich Result Testing tool. You don't need to do anything extra for it to be picked up by Google assistant powered devices.",
  },
];
export const payment = [
  {
    title:
      "How can I get FAQ Page to work with Google assistant powered devices?",
    para: "The FAQPage code generated by this FAQ Page Schema Generator tool will be picked up by both Google Search and Google Assistant powered devices. You just need to install it on your page, you can check if it's working as expected by validating the page with Google’s Rich Result Testing tool. You don't need to do anything extra for it to be picked up by Google assistant powered devices.",
  },
  {
    title: "Does FAQ Snippets work on mobile or desktop?",
    para: "The FAQPage code generated by this FAQ Page Schema Generator tool will be picked up by both Google Search and Google Assistant powered devices. You just need to install it on your page, you can check if it's working as expected by validating the page with Google’s Rich Result Testing tool. You don't need to do anything extra for it to be picked up by Google assistant powered devices.",
  },
  {
    title: "What is the difference between FAQ and QA?",
    para: "The FAQPage code generated by this FAQ Page Schema Generator tool will be picked up by both Google Search and Google Assistant powered devices. You just need to install it on your page, you can check if it's working as expected by validating the page with Google’s Rich Result Testing tool. You don't need to do anything extra for it to be picked up by Google assistant powered devices.",
  },
  {
    title: "Is there a month-to-month payment option?",
    para: "The FAQPage code generated by this FAQ Page Schema Generator tool will be picked up by both Google Search and Google Assistant powered devices. You just need to install it on your page, you can check if it's working as expected by validating the page with Google’s Rich Result Testing tool. You don't need to do anything extra for it to be picked up by Google assistant powered devices.",
  },
];
